# Generated by Django 5.0.1 on 2026-04-23 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(choices=[('feu', 'Feu'), ('eau', 'Eau'), ('vent', 'Vent'), ('terre', 'Terre'), ('ombre', 'Ombre'), ('lumiere', 'Lumière')], max_length=20)),
                ('text', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('type_a', models.CharField(max_length=1)),
                ('type_b', models.CharField(max_length=1)),
                ('type_c', models.CharField(max_length=1)),
                ('type_d', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='RiasecCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('firstname', models.CharField(blank=True, max_length=100, null=True)),
                ('school_class', models.CharField(blank=True, max_length=20, null=True)),
                ('element', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('selected_option', models.CharField(blank=True, max_length=1, null=True)),
                ('riasec_type', models.CharField(blank=True, max_length=1, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fate_95.question')),
            ],
        ),
    ]
