# Generated by Django 5.0.1 on 2026-04-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fate_95', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='element',
            field=models.CharField(choices=[('feu', 'Feu'), ('eau', 'Eau'), ('vent', 'Vent'), ('terre', 'Terre'), ('ombre', 'Ombre'), ('lumiere', 'Lumière'), ('bleu', 'Bleu'), ('jaune', 'Jaune'), ('rouge', 'Rouge'), ('noir', 'Noir'), ('blanc', 'Blanc')], max_length=20),
        ),
    ]
