# Generated by Django 5.2.14 on 2026-05-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fate_95', '0002_alter_question_element'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openai_api_key', models.CharField(default='', max_length=255)),
                ('admin_password', models.CharField(default='', max_length=255)),
                ('session_code', models.CharField(default='', max_length=20)),
                ('session_open', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Configuration Admin',
            },
        ),
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('firstname', models.CharField(default='', max_length=100)),
                ('school_class', models.CharField(default='', max_length=20)),
                ('element', models.CharField(default='', max_length=20)),
                ('quest', models.CharField(default='', max_length=20)),
                ('dominant', models.CharField(default='', max_length=1)),
                ('score_r', models.IntegerField(default=0)),
                ('score_i', models.IntegerField(default=0)),
                ('score_a', models.IntegerField(default=0)),
                ('score_s', models.IntegerField(default=0)),
                ('score_e', models.IntegerField(default=0)),
                ('score_c', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Résultat de partie',
            },
        ),
    ]
