# Generated by Django 5.0.1 on 2026-05-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fate_95', '0002_alter_question_element'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='element',
            field=models.CharField(choices=[('feu', 'Feu'), ('eau', 'Eau'), ('vent', 'Vent'), ('terre', 'Terre'), ('ombre', 'Ombre'), ('lumiere', 'Lumière'), ('bleu', 'Bleu'), ('jaune', 'Jaune'), ('rouge', 'Rouge'), ('noir', 'Noir'), ('blanc', 'Blanc'), ('carre', 'Carré'), ('triangle', 'Triangle'), ('rectangle', 'Rectangle'), ('cercle', 'Cercle'), ('losange', 'Losange'), ('parallelogramme', 'Parallélogramme')], max_length=20),
        ),
    ]
