# Generated by Django 5.2.14 on 2026-05-14 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fate_95', '0003_adminconfig_gameresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Compte admin',
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('label', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_open', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Session de jeu',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='adminconfig',
            name='admin_password',
        ),
        migrations.RemoveField(
            model_name='adminconfig',
            name='session_code',
        ),
        migrations.RemoveField(
            model_name='adminconfig',
            name='session_open',
        ),
        migrations.AddField(
            model_name='gameresult',
            name='game_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='fate_95.gamesession'),
        ),
    ]
