# Generated by Django 5.2.14 on 2026-05-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fate_95', '0004_adminaccount_gamesession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminconfig',
            name='openai_model',
            field=models.CharField(default='gpt-4.1', max_length=50),
        ),
    ]
