# Generated by Django 5.2.14 on 2026-05-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fate_95', '0005_adminconfig_openai_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrientationAdvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('embedding', models.TextField(default='')),
            ],
            options={
                'verbose_name': "Conseil d'orientation",
            },
        ),
        migrations.AddField(
            model_name='adminconfig',
            name='chatbot_prompt',
            field=models.TextField(default=''),
        ),
    ]
